project:
  type: website
  output-dir: docs

website:
  title: "course"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  repo-url: https://github.com/Barry-Menglong-Yao/website-publish
  repo-actions: [edit, issue]
format:
  html:
    theme: cosmo
    css: styles.css



