project:
  type: website
  output-dir: docs

website:
  title: "course"
  repo-url: https://github.com/Barry-Menglong-Yao/website-publish
  repo-actions: [edit, issue]
format:
  html:
    theme: cosmo
    css: styles.css



